#!/usr/bin/env php
<?php

/**
 * This file is part of CodeIgniter 4 framework.
 *
 * (c) CodeIgniter Foundation <admin@codeigniter.com>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

/*
|--------------------------------------------------------------------------
| CodeIgniter command-line tools
|--------------------------------------------------------------------------
|
| The main entry point into the CLI system and allows you to run
| commands and perform maintenance on your application.
|
| Because CodeIgniter can handle CLI requests as just another web request
| this class mainly acts as a passthru to the framework itself.
|
*/

define('SPARKED', true);

/*
 *---------------------------------------------------------------
 * BOOTSTRAP THE APPLICATION
 *---------------------------------------------------------------
 *
 * This process sets up the path constants, loads and registers
 * our autoloader, and loads our environment file, making sure
 * everything is ready for the application to run.
 */

// Refuse to run when called from php-cgi
if (strpos(PHP_SAPI, 'cgi') === 0) {
    exit("The cli tool is not supported when running php-cgi. It needs php-cli to function!\n\n");
}

// We want errors to be shown when setting up the application.
error_reporting(-1);
ini_set('display_errors', '1');

// Load our paths config file
// This is the line that might be causing issues
$pathsConfig = __DIR__ . '/app/Config/Paths.php';

// ^^^ Change this line if you move your application folder

$bootstrap = rtrim($pathsConfig, 'Config/Paths.php') . 'bootstrap.php';
$app       = require realpath($bootstrap) ?: $bootstrap;

// Grab our Console
$console = new CodeIgniter\CLI\Console($app);

// We want errors to be shown when running the application.
error_reporting(-1);
ini_set('display_errors', '1');

$console->run();
